CREATE TABLE IF NOT EXISTS notification_task (
    id BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT      NOT NULL,
    message_text TEXT   NOT NULL,
    message_sent_time   TIMESTAMP NOT NULL
)